### ISSUE TITLE
Password field not populating or in admin in Django 1.6.10

### ISSUE THREAD

**Issue by anthonydb** [dmpayton/django-admin-honeypot#25]
My site's at Django 1.6 and I'm using v 0.4.0 of django-admin-honeypot. For some reason, the password field isn't displaying in the admin, nor is it being populated in the database when I test. Any ideas?

**Comment by mvasilkov** [comment]
@anthonydb Sadly, they purposefully removed it—passwords aren't saved anymore.

In my fork I've reverted the change (while stripping down other things on the way). So if you're feeling particularly adventurous, here it is: https://github.com/mvasilkov/django-trap

In your requirements.txt, it will look like this:
`git+https://github.com/mvasilkov/mysqlclient-python.git`

**Comment by dmpayton** [comment]
Sorry it's taken so long to reply.

Storing the password ended up being a **Bad Idea**, and it was removed a while back. There's a very real chance that an admin could enter their actual password into the honeypot login, which would display it plainly to anyone else with access to the admin or database. **This is a Very Bad Thing**, since the only way to remove it is to delete it at the database level. This exact scenario has happened to myself and others.

It doesn't really matter what password was entered, just that someone was potentially maliciously trying to access the admin. The information that *is* collected -- username, session key, user agent, and IP address -- should be enough.

Please don't store the password.
